services:
  - name: sonic-backend
    type: web
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar /app/target/Sonic-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: ENV
        value: "prod"
    

